// <auto-generated/>

// ----------------------------------------------------------------------
// <copyright file="ArrayOfObjStationData.cs" company="Felsökning">
//      Copyright © Felsökning. All rights reserved.
// </copyright>
// <author>John Bailey</author>
// ----------------------------------------------------------------------
namespace Felsökning.Ireland.IarnródÉireann
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="ArrayOfObjStationData"/> class.
    /// </summary>
    /// <remarks>NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.</remarks>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://api.irishrail.ie/realtime/")]
    [XmlRootAttribute(Namespace = "http://api.irishrail.ie/realtime/", IsNullable = false)]
    public partial class ArrayOfObjStationData
    {

        private ObjStationData[] objStationDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objStationData")]
        public ObjStationData[] objStationData
        {
            get
            {
                return this.objStationDataField;
            }
            set
            {
                this.objStationDataField = value;
            }
        }
    }
}