// <auto-generated/>

// ----------------------------------------------------------------------
// <copyright file="ObjStation.cs" company="Felsökning">
//      Copyright © Felsökning. All rights reserved.
// </copyright>
// <author>John Bailey</author>
// ----------------------------------------------------------------------
namespace Felsökning.Ireland.IarnródÉireann
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="ObjStation"/> class.
    /// </summary>
    /// <remarks>NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.</remarks>
    [Serializable()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://api.irishrail.ie/realtime/")]
    public partial class ObjStation
    {

        private string stationDescField;

        private string stationAliasField;

        private decimal stationLatitudeField;

        private decimal stationLongitudeField;

        private string stationCodeField;

        private ushort stationIdField;

        /// <remarks/>
        public string StationDesc
        {
            get
            {
                return this.stationDescField;
            }
            set
            {
                this.stationDescField = value;
            }
        }

        /// <remarks/>
        public string StationAlias
        {
            get
            {
                return this.stationAliasField;
            }
            set
            {
                this.stationAliasField = value;
            }
        }

        /// <remarks/>
        public decimal StationLatitude
        {
            get
            {
                return this.stationLatitudeField;
            }
            set
            {
                this.stationLatitudeField = value;
            }
        }

        /// <remarks/>
        public decimal StationLongitude
        {
            get
            {
                return this.stationLongitudeField;
            }
            set
            {
                this.stationLongitudeField = value;
            }
        }

        /// <remarks/>
        public string StationCode
        {
            get
            {
                return this.stationCodeField;
            }
            set
            {
                this.stationCodeField = value;
            }
        }

        /// <remarks/>
        public ushort StationId
        {
            get
            {
                return this.stationIdField;
            }
            set
            {
                this.stationIdField = value;
            }
        }
    }
}